server:
  port: 8091
spring:
  application:
    name: "EmployeeManage"
  datasource:
    url: jdbc:mysql://localhost:3306/employee_manage
    username: root
    password: root
  jpa:
    show-sql: true